/*
 * Student API
 * Student API using swagger.io by Siddharth Raj
 *
 * OpenAPI spec version: 1.0.0
 * Contact: siddharth.raj2019@vitbhopal.ac.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
